---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  annotations:
    fluxcd.io/tag.podinfo: glob:3.1.*
spec:
  replicas: 3
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - name: podinfo
        image: quay.io/stefanprodan/podinfo:3.0.0
        ports:
        - containerPort: 3000
